((nil . ((projectile-indexing-method . native)
         (projectile-enable-caching . t)
         (projectile-test-command . "python -m unittest discover")
         (python-check . "python -m pylint")
         (py-autopep8 t)
         (py-autopep8-enable-on-save)
         )))
